[build]
  command = "pnpm typecheck && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[secrets]
  SECRETS_SCAN_OMIT_KEYS = ["VITE_API_KEY"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 