[build]
  command = "pnpm typecheck && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_KEY = "your_api_url_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 